# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-04-09 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='course',
        ),
    ]
